CREATE DATABASE IF NOT EXISTS jeffmusic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE jeffmusic;

CREATE TABLE IF NOT EXISTS shows (
  id INT AUTO_INCREMENT PRIMARY KEY,
  place VARCHAR(255) NOT NULL,
  day VARCHAR(100) NOT NULL,
  time VARCHAR(50) DEFAULT NULL,
  available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS photos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(500) NOT NULL,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) DEFAULT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS videos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(500) NOT NULL,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) DEFAULT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contact_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  message TEXT NOT NULL,
  status ENUM('pending', 'contacted', 'confirmed', 'cancelled') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS site_sections (
  id INT AUTO_INCREMENT PRIMARY KEY,
  section_key VARCHAR(50) NOT NULL UNIQUE,
  media_url VARCHAR(500) DEFAULT NULL,
  media_type VARCHAR(10) DEFAULT NULL,
  title_es VARCHAR(255) DEFAULT NULL,
  title_en VARCHAR(255) DEFAULT NULL,
  subtitle_es VARCHAR(500) DEFAULT NULL,
  subtitle_en VARCHAR(500) DEFAULT NULL,
  text1_es TEXT DEFAULT NULL,
  text1_en TEXT DEFAULT NULL,
  text2_es TEXT DEFAULT NULL,
  text2_en TEXT DEFAULT NULL,
  text3_es TEXT DEFAULT NULL,
  text3_en TEXT DEFAULT NULL,
  data_json TEXT DEFAULT NULL COMMENT 'JSON data for flexible fields (e.g. per-month calendar backgrounds)',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
